<?php

// Exit if accessed directly
if ( !defined('ABSPATH')) exit;

/**
 *
 * WARNING: Please do not edit this file in any way
 *
 * load the theme function files
 */
require ( get_template_directory() . '/core/includes/functions.php' );
require ( get_template_directory() . '/core/includes/theme-options.php' );
require ( get_template_directory() . '/core/includes/post-custom-meta.php' );
require ( get_template_directory() . '/core/includes/tha-theme-hooks.php' );
require ( get_template_directory() . '/core/includes/hooks.php' );
require ( get_template_directory() . '/core/includes/version.php' );


function replace_content($content)
{
  //add content that you wish to replace to this array
  $search  = array('™', 'é', '–', '‘', '’', '“', '”', 'Â', 'â€“', '[three type="joint" height="260"] [text font="Lucida Grande" other="font-weight: bold;" size="17"]','[/text] [text color="#666"]', '[/text][/three]','[three_middle type="joint" height="260"] [text font="Lucida Grande" other="font-weight: bold;" size="17"]appsFreedom in the News[/text][text color="#666"][blogroll limit="3" orderby="date" order="ASC" category="34"][/text][/three_middle]','[three_last type="joint" height="260"] [text font="Lucida Grande" other="font-weight: bold;" size="17"]','[/text] [/three_last]','â€œ','â€','“');
  //add content that will replace old content to this array
  $replace = array('&#153;', 'é', '&#8212;', '&#39;', '&#39;', '“', '”', '', '', '', '','','','','','','"');

  $content = str_replace($search, $replace, $content);
  return $content;
}
add_filter('the_content', 'replace_content');
add_filter('the_excerpt', 'replace_content');
add_filter('the_title', 'replace_content');